"""Create complete database schema

Revision ID: 3ce77a4e1e5a
Revises: 
Create Date: 2026-01-11 22:31:14.827104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce77a4e1e5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('openid', sa.String(length=100), nullable=True, comment='微信openid'),
    sa.Column('unionid', sa.String(length=100), nullable=True, comment='微信unionid'),
    sa.Column('session_key', sa.String(length=100), nullable=True, comment='微信session_key'),
    sa.Column('subscribe_scene', sa.String(length=100), nullable=True, comment='关注场景'),
    sa.Column('subscribe_time', sa.DateTime(timezone=True), nullable=True, comment='关注时间'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='手机号'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('hashed_password', sa.String(length=255), nullable=True, comment='加密密码'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('avatar', sa.String(length=500), nullable=True, comment='头像URL'),
    sa.Column('real_name', sa.String(length=50), nullable=True, comment='真实姓名'),
    sa.Column('id_card', sa.String(length=18), nullable=True, comment='身份证号'),
    sa.Column('gender', sa.SmallInteger(), nullable=True, comment='性别：0未知，1男，2女'),
    sa.Column('current_city', sa.String(length=50), nullable=True, comment='当前城市'),
    sa.Column('hometown_city', sa.String(length=50), nullable=True, comment='家乡城市（返乡用户关键字段）'),
    sa.Column('preferred_districts', sa.JSON(), nullable=True, comment='偏好区域数组'),
    sa.Column('user_type', sa.SmallInteger(), nullable=True, comment='用户类型：1普通用户，2改善用户，3投资用户'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('is_superuser', sa.Boolean(), nullable=True, comment='是否超级用户'),
    sa.Column('is_verified', sa.Boolean(), nullable=True, comment='是否实名认证'),
    sa.Column('is_agent', sa.Boolean(), nullable=True, comment='是否经纪人'),
    sa.Column('agent_license', sa.String(length=50), nullable=True, comment='经纪人执业证号'),
    sa.Column('source_channel', sa.String(length=50), nullable=True, comment='来源渠道'),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True, comment='UTM活动'),
    sa.Column('registration_ip', sa.String(length=50), nullable=True, comment='注册IP'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态：1正常，0禁用'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='最后登录时间'),
    sa.Column('last_login_ip', sa.String(length=50), nullable=True, comment='最后登录IP'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间（软删除）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_hometown_city'), 'users', ['hometown_city'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_openid'), 'users', ['openid'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_unionid'), 'users', ['unionid'], unique=True)
    op.create_table('agent_availability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False, comment='经纪人ID'),
    sa.Column('available_date', sa.Date(), nullable=False, comment='可用日期'),
    sa.Column('available_slots', sa.JSON(), nullable=True, comment="可用时段数组，格式：[{'start': '09:00', 'end': '12:00'}, ...]"),
    sa.Column('is_fully_booked', sa.Boolean(), nullable=True, comment='是否已全部预约'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'available_date', name='uq_agent_availability')
    )
    op.create_index(op.f('ix_agent_availability_agent_id'), 'agent_availability', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_availability_available_date'), 'agent_availability', ['available_date'], unique=False)
    op.create_index(op.f('ix_agent_availability_id'), 'agent_availability', ['id'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_no', sa.String(length=20), nullable=True, comment='房源编号'),
    sa.Column('agent_id', sa.Integer(), nullable=False, comment='经纪人ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='房源标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='房源描述'),
    sa.Column('property_type', sa.SmallInteger(), nullable=False, comment='房产类型：1住宅，2商铺，3写字楼，4别墅'),
    sa.Column('transaction_type', sa.SmallInteger(), nullable=False, comment='交易类型：1出售，2出租'),
    sa.Column('province', sa.String(length=50), nullable=False, comment='省份'),
    sa.Column('city', sa.String(length=50), nullable=False, comment='城市'),
    sa.Column('district', sa.String(length=50), nullable=False, comment='区/县'),
    sa.Column('town', sa.String(length=50), nullable=True, comment='镇/街道'),
    sa.Column('village', sa.String(length=50), nullable=True, comment='村/社区'),
    sa.Column('detail_address', sa.String(length=200), nullable=True, comment='详细地址'),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True, comment='经度'),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True, comment='纬度'),
    sa.Column('total_price', sa.Integer(), nullable=True, comment='总价（元）'),
    sa.Column('unit_price', sa.Integer(), nullable=True, comment='单价（元/㎡）'),
    sa.Column('area', sa.Numeric(precision=6, scale=2), nullable=False, comment='建筑面积（㎡）'),
    sa.Column('room_count', sa.SmallInteger(), nullable=True, comment='室数'),
    sa.Column('hall_count', sa.SmallInteger(), nullable=True, comment='厅数'),
    sa.Column('bathroom_count', sa.SmallInteger(), nullable=True, comment='卫数'),
    sa.Column('floor_info', sa.String(length=50), nullable=True, comment='楼层信息'),
    sa.Column('total_floors', sa.SmallInteger(), nullable=True, comment='总层数'),
    sa.Column('build_year', sa.SmallInteger(), nullable=True, comment='建成年份'),
    sa.Column('decoration_type', sa.SmallInteger(), nullable=True, comment='装修类型'),
    sa.Column('school_district', sa.String(length=100), nullable=True, comment='学区信息（返乡用户重点关注）'),
    sa.Column('transportation', sa.JSON(), nullable=True, comment='交通配套数组'),
    sa.Column('surrounding_facilities', sa.JSON(), nullable=True, comment='周边设施详情'),
    sa.Column('property_rights_years', sa.SmallInteger(), nullable=True, comment='产权年限'),
    sa.Column('down_payment_ratio', sa.Numeric(precision=3, scale=1), nullable=True, comment='首付比例'),
    sa.Column('cover_image_url', sa.Text(), nullable=True, comment='封面图片URL'),
    sa.Column('video_urls', sa.JSON(), nullable=True, comment='视频链接数组'),
    sa.Column('vr_url', sa.Text(), nullable=True, comment='VR看房链接'),
    sa.Column('has_vr', sa.Boolean(), nullable=True, comment='是否有VR'),
    sa.Column('has_video', sa.Boolean(), nullable=True, comment='是否有视频'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态：1在售，2已售，3下架'),
    sa.Column('audit_status', sa.SmallInteger(), nullable=True, comment='审核状态：0待审核，1已通过，2已拒绝'),
    sa.Column('verify_status', sa.Boolean(), nullable=True, comment='真实性验证'),
    sa.Column('view_count', sa.Integer(), nullable=True, comment='浏览次数'),
    sa.Column('favorite_count', sa.Integer(), nullable=True, comment='收藏次数'),
    sa.Column('inquiry_count', sa.Integer(), nullable=True, comment='咨询次数'),
    sa.Column('share_count', sa.Integer(), nullable=True, comment='分享次数'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签数组'),
    sa.Column('keywords', sa.String(length=500), nullable=True, comment='关键词'),
    sa.Column('contact_phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('contact_name', sa.String(length=50), nullable=True, comment='联系人姓名'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间（软删除）'),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_properties_advanced', 'properties', ['city', 'district', 'property_type', 'transaction_type', 'total_price', 'area', 'status'], unique=False)
    op.create_index('idx_properties_location', 'properties', ['city', 'district', 'town'], unique=False)
    op.create_index('idx_properties_price_area', 'properties', ['total_price', 'area'], unique=False)
    op.create_index(op.f('ix_properties_agent_id'), 'properties', ['agent_id'], unique=False)
    op.create_index(op.f('ix_properties_city'), 'properties', ['city'], unique=False)
    op.create_index(op.f('ix_properties_district'), 'properties', ['district'], unique=False)
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.create_index(op.f('ix_properties_property_no'), 'properties', ['property_no'], unique=True)
    op.create_index(op.f('ix_properties_status'), 'properties', ['status'], unique=False)
    op.create_index(op.f('ix_properties_town'), 'properties', ['town'], unique=False)
    op.create_index(op.f('ix_properties_unit_price'), 'properties', ['unit_price'], unique=False)
    op.create_table('user_behaviors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('behavior_type', sa.SmallInteger(), nullable=False, comment='行为类型'),
    sa.Column('target_type', sa.SmallInteger(), nullable=False, comment='目标类型'),
    sa.Column('target_id', sa.Integer(), nullable=False, comment='目标ID'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='停留时长（秒）'),
    sa.Column('action_data', sa.JSON(), nullable=True, comment='详细行为数据'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_behaviors_type', 'user_behaviors', ['user_id', 'behavior_type', 'target_type'], unique=False)
    op.create_index('idx_user_behaviors_user_target', 'user_behaviors', ['user_id', 'target_type', 'target_id'], unique=False)
    op.create_index(op.f('ix_user_behaviors_created_at'), 'user_behaviors', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_behaviors_id'), 'user_behaviors', ['id'], unique=False)
    op.create_index(op.f('ix_user_behaviors_user_id'), 'user_behaviors', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('budget_min', sa.Integer(), nullable=True, comment='最小预算（万元）'),
    sa.Column('budget_max', sa.Integer(), nullable=True, comment='最大预算（万元）'),
    sa.Column('area_min', sa.Integer(), nullable=True, comment='最小面积（㎡）'),
    sa.Column('area_max', sa.Integer(), nullable=True, comment='最大面积（㎡）'),
    sa.Column('preferred_property_types', sa.JSON(), nullable=True, comment='偏好户型类型数组'),
    sa.Column('preferred_locations', sa.JSON(), nullable=True, comment='偏好位置数组'),
    sa.Column('has_children', sa.Boolean(), nullable=True, comment='是否有孩子（学区需求）'),
    sa.Column('price_weight', sa.Numeric(precision=3, scale=2), nullable=True, comment='价格权重'),
    sa.Column('location_weight', sa.Numeric(precision=3, scale=2), nullable=True, comment='位置权重'),
    sa.Column('school_weight', sa.Numeric(precision=3, scale=2), nullable=True, comment='学区权重'),
    sa.Column('transport_weight', sa.Numeric(precision=3, scale=2), nullable=True, comment='交通权重'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appointment_no', sa.String(length=30), nullable=True, comment='预约编号'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('property_id', sa.Integer(), nullable=False, comment='房源ID'),
    sa.Column('agent_id', sa.Integer(), nullable=False, comment='经纪人ID'),
    sa.Column('appointment_date', sa.Date(), nullable=False, comment='预约日期'),
    sa.Column('appointment_time', sa.Time(), nullable=False, comment='预约时间'),
    sa.Column('duration_minutes', sa.Integer(), nullable=True, comment='预约时长（分钟）'),
    sa.Column('appointment_type', sa.SmallInteger(), nullable=True, comment='预约类型：1实地看房，2视频看房，3VR看房'),
    sa.Column('participants_count', sa.SmallInteger(), nullable=True, comment='参与人数'),
    sa.Column('contact_name', sa.String(length=50), nullable=False, comment='联系人姓名'),
    sa.Column('contact_phone', sa.String(length=20), nullable=False, comment='联系电话'),
    sa.Column('contact_wechat', sa.String(length=50), nullable=True, comment='微信号'),
    sa.Column('special_requirements', sa.Text(), nullable=True, comment='特殊要求'),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态：0已取消，1待确认，2已确认，3已完成'),
    sa.Column('confirmation_status', sa.SmallInteger(), nullable=True, comment='确认状态'),
    sa.Column('cancel_reason', sa.Text(), nullable=True, comment='取消原因'),
    sa.Column('cancel_time', sa.DateTime(timezone=True), nullable=True, comment='取消时间'),
    sa.Column('feedback_score', sa.SmallInteger(), nullable=True, comment='满意度评分1-5'),
    sa.Column('feedback_comment', sa.Text(), nullable=True, comment='反馈评论'),
    sa.Column('is_interested', sa.Boolean(), nullable=True, comment='是否感兴趣'),
    sa.Column('next_followup', sa.DateTime(timezone=True), nullable=True, comment='下次跟进时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True, comment='确认时间'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间（软删除）'),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_appointments_composite', 'appointments', ['user_id', 'property_id', 'status', 'appointment_date'], unique=False)
    op.create_index('idx_appointments_time_range', 'appointments', ['appointment_date', 'appointment_time', 'status'], unique=False)
    op.create_index(op.f('ix_appointments_agent_id'), 'appointments', ['agent_id'], unique=False)
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_appointment_no'), 'appointments', ['appointment_no'], unique=True)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_property_id'), 'appointments', ['property_id'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index(op.f('ix_appointments_user_id'), 'appointments', ['user_id'], unique=False)
    op.create_table('property_favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('property_id', sa.Integer(), nullable=False, comment='房源ID'),
    sa.Column('price_alert', sa.Boolean(), nullable=True, comment='价格变动提醒'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'property_id', name='uq_user_property_favorite')
    )
    op.create_index(op.f('ix_property_favorites_id'), 'property_favorites', ['id'], unique=False)
    op.create_index(op.f('ix_property_favorites_property_id'), 'property_favorites', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_favorites_user_id'), 'property_favorites', ['user_id'], unique=False)
    op.create_table('property_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False, comment='房源ID'),
    sa.Column('image_url', sa.Text(), nullable=False, comment='图片URL'),
    sa.Column('thumbnail_url', sa.Text(), nullable=True, comment='缩略图URL'),
    sa.Column('image_type', sa.SmallInteger(), nullable=True, comment='图片类型：0普通，1客厅，2卧室，3厨房，4卫生间，5阳台'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序顺序'),
    sa.Column('is_cover', sa.Boolean(), nullable=True, comment='是否封面图'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小（字节）'),
    sa.Column('width', sa.Integer(), nullable=True, comment='宽度（像素）'),
    sa.Column('height', sa.Integer(), nullable=True, comment='高度（像素）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_images_id'), 'property_images', ['id'], unique=False)
    op.create_index(op.f('ix_property_images_property_id'), 'property_images', ['property_id'], unique=False)
    op.create_table('short_videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_no', sa.String(length=30), nullable=True, comment='视频编号'),
    sa.Column('creator_id', sa.Integer(), nullable=False, comment='创建者ID'),
    sa.Column('property_id', sa.Integer(), nullable=True, comment='关联房源ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='视频标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='视频描述'),
    sa.Column('video_url', sa.Text(), nullable=False, comment='视频URL'),
    sa.Column('cover_image_url', sa.Text(), nullable=True, comment='封面图片URL'),
    sa.Column('video_duration', sa.Integer(), nullable=True, comment='视频时长（秒）'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小（字节）'),
    sa.Column('platform_tags', sa.JSON(), nullable=True, comment='平台标签数组：抖音、快手、小红书等'),
    sa.Column('is_published', sa.Boolean(), nullable=True, comment='是否已发布'),
    sa.Column('publish_time', sa.DateTime(timezone=True), nullable=True, comment='发布时间'),
    sa.Column('view_count', sa.Integer(), nullable=True, comment='播放次数'),
    sa.Column('like_count', sa.Integer(), nullable=True, comment='点赞次数'),
    sa.Column('comment_count', sa.Integer(), nullable=True, comment='评论次数'),
    sa.Column('share_count', sa.Integer(), nullable=True, comment='分享次数'),
    sa.Column('favorite_count', sa.Integer(), nullable=True, comment='收藏次数'),
    sa.Column('review_status', sa.SmallInteger(), nullable=True, comment='审核状态：0待审核，1已通过，2已拒绝'),
    sa.Column('review_note', sa.Text(), nullable=True, comment='审核备注'),
    sa.Column('reviewer_id', sa.Integer(), nullable=True, comment='审核人ID'),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True, comment='审核时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间（软删除）'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_short_videos_creator_published', 'short_videos', ['creator_id', 'is_published', 'created_at'], unique=False)
    op.create_index(op.f('ix_short_videos_creator_id'), 'short_videos', ['creator_id'], unique=False)
    op.create_index(op.f('ix_short_videos_id'), 'short_videos', ['id'], unique=False)
    op.create_index(op.f('ix_short_videos_is_published'), 'short_videos', ['is_published'], unique=False)
    op.create_index(op.f('ix_short_videos_property_id'), 'short_videos', ['property_id'], unique=False)
    op.create_index(op.f('ix_short_videos_review_status'), 'short_videos', ['review_status'], unique=False)
    op.create_index(op.f('ix_short_videos_video_no'), 'short_videos', ['video_no'], unique=True)
    op.create_table('video_recommendations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('video_id', sa.Integer(), nullable=False, comment='视频ID'),
    sa.Column('base_score', sa.Numeric(precision=5, scale=4), nullable=True, comment='基础得分'),
    sa.Column('user_preference_score', sa.Numeric(precision=5, scale=4), nullable=True, comment='用户偏好得分'),
    sa.Column('location_score', sa.Numeric(precision=5, scale=4), nullable=True, comment='地理位置得分'),
    sa.Column('recency_score', sa.Numeric(precision=5, scale=4), nullable=True, comment='时效性得分'),
    sa.Column('engagement_score', sa.Numeric(precision=5, scale=4), nullable=True, comment='互动率得分'),
    sa.Column('final_score', sa.Numeric(precision=6, scale=4), nullable=False, comment='最终得分'),
    sa.Column('is_shown', sa.Boolean(), nullable=True, comment='是否已展示'),
    sa.Column('shown_at', sa.DateTime(timezone=True), nullable=True, comment='展示时间'),
    sa.Column('clicked', sa.Boolean(), nullable=True, comment='是否已点击'),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True, comment='点击时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['short_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_video_rec_realtime', 'video_recommendations', ['user_id', 'final_score', 'is_shown'], unique=False)
    op.create_index('idx_video_rec_user_score', 'video_recommendations', ['user_id', 'final_score'], unique=False)
    op.create_index(op.f('ix_video_recommendations_final_score'), 'video_recommendations', ['final_score'], unique=False)
    op.create_index(op.f('ix_video_recommendations_id'), 'video_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_video_recommendations_is_shown'), 'video_recommendations', ['is_shown'], unique=False)
    op.create_index(op.f('ix_video_recommendations_user_id'), 'video_recommendations', ['user_id'], unique=False)
    op.create_index(op.f('ix_video_recommendations_video_id'), 'video_recommendations', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_recommendations_video_id'), table_name='video_recommendations')
    op.drop_index(op.f('ix_video_recommendations_user_id'), table_name='video_recommendations')
    op.drop_index(op.f('ix_video_recommendations_is_shown'), table_name='video_recommendations')
    op.drop_index(op.f('ix_video_recommendations_id'), table_name='video_recommendations')
    op.drop_index(op.f('ix_video_recommendations_final_score'), table_name='video_recommendations')
    op.drop_index('idx_video_rec_user_score', table_name='video_recommendations')
    op.drop_index('idx_video_rec_realtime', table_name='video_recommendations')
    op.drop_table('video_recommendations')
    op.drop_index(op.f('ix_short_videos_video_no'), table_name='short_videos')
    op.drop_index(op.f('ix_short_videos_review_status'), table_name='short_videos')
    op.drop_index(op.f('ix_short_videos_property_id'), table_name='short_videos')
    op.drop_index(op.f('ix_short_videos_is_published'), table_name='short_videos')
    op.drop_index(op.f('ix_short_videos_id'), table_name='short_videos')
    op.drop_index(op.f('ix_short_videos_creator_id'), table_name='short_videos')
    op.drop_index('idx_short_videos_creator_published', table_name='short_videos')
    op.drop_table('short_videos')
    op.drop_index(op.f('ix_property_images_property_id'), table_name='property_images')
    op.drop_index(op.f('ix_property_images_id'), table_name='property_images')
    op.drop_table('property_images')
    op.drop_index(op.f('ix_property_favorites_user_id'), table_name='property_favorites')
    op.drop_index(op.f('ix_property_favorites_property_id'), table_name='property_favorites')
    op.drop_index(op.f('ix_property_favorites_id'), table_name='property_favorites')
    op.drop_table('property_favorites')
    op.drop_index(op.f('ix_appointments_user_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_property_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_no'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_agent_id'), table_name='appointments')
    op.drop_index('idx_appointments_time_range', table_name='appointments')
    op.drop_index('idx_appointments_composite', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_behaviors_user_id'), table_name='user_behaviors')
    op.drop_index(op.f('ix_user_behaviors_id'), table_name='user_behaviors')
    op.drop_index(op.f('ix_user_behaviors_created_at'), table_name='user_behaviors')
    op.drop_index('idx_user_behaviors_user_target', table_name='user_behaviors')
    op.drop_index('idx_user_behaviors_type', table_name='user_behaviors')
    op.drop_table('user_behaviors')
    op.drop_index(op.f('ix_properties_unit_price'), table_name='properties')
    op.drop_index(op.f('ix_properties_town'), table_name='properties')
    op.drop_index(op.f('ix_properties_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_property_no'), table_name='properties')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_district'), table_name='properties')
    op.drop_index(op.f('ix_properties_city'), table_name='properties')
    op.drop_index(op.f('ix_properties_agent_id'), table_name='properties')
    op.drop_index('idx_properties_price_area', table_name='properties')
    op.drop_index('idx_properties_location', table_name='properties')
    op.drop_index('idx_properties_advanced', table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_agent_availability_id'), table_name='agent_availability')
    op.drop_index(op.f('ix_agent_availability_available_date'), table_name='agent_availability')
    op.drop_index(op.f('ix_agent_availability_agent_id'), table_name='agent_availability')
    op.drop_table('agent_availability')
    op.drop_index(op.f('ix_users_unionid'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_openid'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_hometown_city'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
