// 灵山公交线路数据
const lines = [
  {
    id: "3路",
    type: "城区",
    start: "建材市场",
    end: "职校",
    time: "06:00-21:00",
    interval: "15分钟",
    price: "0元",
    duration: "40分钟",
    stations: [
      {name: "建材市场", duration: 0},
      {name: "柑子园", duration: 3},
      {name: "江南邮政", duration: 6},
      {name: "中医院", duration: 9},
      {name: "泰丰百货", duration: 12},
      {name: "步行街", duration: 15},
      {name: "红十字会", duration: 18},
      {name: "国鹏宾馆", duration: 21},
      {name: "南站", duration: 24},
      {name: "移动公司", duration: 27},
      {name: "教育局", duration: 30},
      {name: "交警大队", duration: 33},
      {name: "兴莱鞋厂", duration: 36},
      {name: "职校", duration: 40}
    ]
  },
  {
    id: "101路",
    type: "城区",
    start: "鹏大汽车城",
    end: "园丰牧业",
    time: "08:00-23:30",
    interval: "12分钟",
    price: "2元",
    duration: "55分钟",
    stations: [
      {name: "鹏大汽车城", duration: 0},
      {name: "招呼站", duration: 2},
      {name: "灵山职校", duration: 5},
      {name: "灵山五幼", duration: 8},
      {name: "交警大队", duration: 11},
      {name: "华源大厦", duration: 14},
      {name: "教育局", duration: 17},
      {name: "中国移动", duration: 20},
      {name: "汽车南站", duration: 23},
      {name: "农业农村局", duration: 26},
      {name: "国鹏大酒店", duration: 29},
      {name: "三海农行", duration: 32},
      {name: "步行街", duration: 35},
      {name: "人民医院路口", duration: 38},
      {name: "中医院", duration: 41},
      {name: "招呼站", duration: 43},
      {name: "江南邮政局", duration: 45},
      {name: "灵山人民银行", duration: 47},
      {name: "旧交通局", duration: 49},
      {name: "第二人民医院", duration: 51},
      {name: "交通局", duration: 53},
      {name: "园丰牧业", duration: 55}
    ]
  },
  {
    id: "102路",
    type: "城区",
    start: "汽车南站",
    end: "洲塘村",
    time: "08:00-23:30",
    interval: "15分钟",
    price: "0元",
    duration: "30分钟",
    stations: [
      {name: "汽车南站", duration: 0},
      {name: "招呼站", duration: 3},
      {name: "爱婴早教托管中心", duration: 6},
      {name: "步行街", duration: 9},
      {name: "灵山汽车站", duration: 12},
      {name: "招呼站", duration: 15},
      {name: "中医院", duration: 18},
      {name: "新洲中学", duration: 22},
      {name: "招呼站", duration: 26},
      {name: "洲塘村", duration: 30}
    ]
  },
  {
    id: "106路",
    type: "城区",
    start: "大琴垌小学",
    end: "华源大厦",
    time: "08:00-23:30",
    interval: "15分钟",
    price: "0元",
    duration: "42分钟",
    stations: [
      {name: "大琴垌小学", duration: 0},
      {name: "招呼站", duration: 3},
      {name: "三博", duration: 6},
      {name: "招呼站", duration: 9},
      {name: "灵山残疾人联合会培训基地", duration: 12},
      {name: "聚龙湾新城", duration: 15},
      {name: "聚龙湾幼儿园", duration: 18},
      {name: "好万家超市", duration: 21},
      {name: "县公安局", duration: 24},
      {name: "金耳朵电器城", duration: 27},
      {name: "步行街", duration: 30},
      {name: "六峰山", duration: 33},
      {name: "中医院宿舍", duration: 36},
      {name: "汽车南站", duration: 38},
      {name: "教育局", duration: 40},
      {name: "华源大厦", duration: 42}
    ]
  },
  {
    id: "210路",
    type: "城乡",
    start: "烟墩政府",
    end: "外国语学校",
    time: "06:48-17:23",
    interval: "25分钟",
    price: "7元",
    duration: "20分钟",
    stations: [
      {name: "烟墩政府", duration: 0},
      {name: "勒菜路口", duration: 10},
      {name: "外国语学校", duration: 20}
    ]
  },
  {
    id: "502路",
    type: "城乡",
    start: "太平镇",
    end: "园丰牧业",
    time: "06:30-18:10",
    interval: "30分钟",
    price: "19.9元",
    duration: "65分钟",
    stations: [
      {name: "太平镇", duration: 0},
      {name: "三隆", duration: 35},
      {name: "交通局", duration: 55},
      {name: "园丰牧业", duration: 65}
    ]
  },
  {
    id: "601路",
    type: "城乡",
    start: "新妇幼保健院",
    end: "睦村",
    time: "07:59-17:33",
    interval: "30分钟",
    price: "10元",
    duration: "90分钟",
    stations: [
      {name: "新妇幼保健院", duration: 0},
      {name: "华源大厦", duration: 8},
      {name: "财政局", duration: 15},
      {name: "汽车南站", duration: 22},
      {name: "外语学校", duration: 30},
      {name: "六峰公园", duration: 38},
      {name: "万象城", duration: 45},
      {name: "实验小学", duration: 52},
      {name: "旧总站", duration: 60},
      {name: "聚龙湾", duration: 68},
      {name: "上东区", duration: 78},
      {name: "睦村", duration: 90}
    ]
  },
  {
    id: "618路",
    type: "城乡",
    start: "新中医院",
    end: "独岭村",
    time: "06:00-18:30",
    interval: "25分钟",
    price: "15元",
    duration: "50分钟",
    stations: [
      {name: "新中医院", duration: 0},
      {name: "湘桂广场", duration: 8},
      {name: "环秀桥大花坛", duration: 16},
      {name: "六峰山大门", duration: 24},
      {name: "灵山中学", duration: 32},
      {name: "三勤村", duration: 42},
      {name: "独岭村", duration: 50}
    ]
  },
  {
    id: "7路",
    type: "城乡",
    start: "新院村委",
    end: "二医院",
    time: "06:00-21:00",
    interval: "20分钟",
    price: "6元",
    duration: "45分钟",
    stations: [
      {name: "新院村委", duration: 0},
      {name: "斑鱼塘", duration: 5},
      {name: "容家", duration: 10},
      {name: "云洲中学", duration: 15},
      {name: "新洲中学", duration: 20},
      {name: "南站", duration: 25},
      {name: "国鹏宾馆", duration: 30},
      {name: "红十字会", duration: 33},
      {name: "三吨桥", duration: 36},
      {name: "江南邮政", duration: 39},
      {name: "旧交通局", duration: 42},
      {name: "二医院", duration: 45}
    ]
  },
  {
    id: "8012路",
    type: "城乡",
    start: "那隆",
    end: "灵山图书馆",
    time: "07:30-17:30",
    interval: "25分钟",
    price: "0元",
    duration: "65分钟",
    stations: [
      {name: "那隆", duration: 0},
      {name: "那隆卫生院", duration: 4},
      {name: "横江岭", duration: 8},
      {name: "芳塘村", duration: 12},
      {name: "柑子塘", duration: 16},
      {name: "长福村", duration: 20},
      {name: "石岭垌", duration: 24},
      {name: "新田村", duration: 28},
      {name: "梓木村委", duration: 32},
      {name: "石子岭", duration: 36},
      {name: "香荔园", duration: 40},
      {name: "龙武庄园", duration: 44},
      {name: "独岭村", duration: 48},
      {name: "黄屋水", duration: 52},
      {name: "三勒村", duration: 55},
      {name: "三海中学", duration: 58},
      {name: "金龙中学", duration: 60},
      {name: "灵山中学路口", duration: 62},
      {name: "灵山中学", duration: 63},
      {name: "灵山图书馆", duration: 65}
    ]
  },
  {
    id: "8018路",
    type: "城乡",
    start: "大平",
    end: "二医院",
    time: "07:00-17:30",
    interval: "25分钟",
    price: "9元",
    duration: "120分钟",
    stations: [
      {name: "大平", duration: 0},
      {name: "那垌", duration: 3},
      {name: "六角塘", duration: 6},
      {name: "樟木林", duration: 9},
      {name: "那隆中学", duration: 12},
      {name: "那隆客运站", duration: 15},
      {name: "那隆派出所", duration: 18},
      {name: "那隆收费站", duration: 21},
      {name: "路司村", duration: 24},
      {name: "龙窟", duration: 27},
      {name: "檀圩镇政府", duration: 30},
      {name: "檀圩街", duration: 33},
      {name: "天山中学", duration: 36},
      {name: "天山电子厂", duration: 39},
      {name: "见田", duration: 42},
      {name: "鹏大汽车城", duration: 45},
      {name: "宇峰工业园", duration: 48},
      {name: "十里工业园", duration: 51},
      {name: "职校", duration: 54},
      {name: "灵山五幼", duration: 57},
      {name: "兴莱鞋厂", duration: 60},
      {name: "交警大队", duration: 63},
      {name: "华源大厦", duration: 66},
      {name: "教育局", duration: 69},
      {name: "中国移动", duration: 72},
      {name: "总站路口", duration: 75},
      {name: "农业农村局", duration: 78},
      {name: "国鹏大酒店", duration: 81},
      {name: "三海农行", duration: 84},
      {name: "三顿桥", duration: 87},
      {name: "江南邮政", duration: 90},
      {name: "旧交通局", duration: 93},
      {name: "二医院", duration: 120}
    ]
  },
  {
    id: "806路",
    type: "城乡",
    start: "平南街",
    end: "新中医院",
    time: "06:30-18:30",
    interval: "20分钟",
    price: "5元",
    duration: "55分钟",
    stations: [
      {name: "平南街", duration: 0},
      {name: "平南中学", duration: 4},
      {name: "平南客运站", duration: 8},
      {name: "平南新城", duration: 12},
      {name: "大洋村", duration: 16},
      {name: "塘肚村", duration: 20},
      {name: "广西正久职业学校", duration: 24},
      {name: "六峰欢乐世界", duration: 28},
      {name: "锦绣广场", duration: 32},
      {name: "旧总站", duration: 36},
      {name: "旧中医院", duration: 40},
      {name: "丰江市场", duration: 44},
      {name: "湘桂广场", duration: 48},
      {name: "湘桂小区东", duration: 51},
      {name: "海灵加油站", duration: 53},
      {name: "新中医院", duration: 55}
    ]
  },
  {
    id: "8011路",
    type: "城乡",
    start: "六峰文化步行街",
    end: "那隆中学",
    time: "06:40-18:00",
    interval: "20分钟",
    price: "5元",
    duration: "60分钟",
    stations: [
      {name: "六峰文化步行街", duration: 0},
      {name: "三海农行", duration: 3},
      {name: "中医院宿舍", duration: 6},
      {name: "农业局", duration: 9},
      {name: "汽车总站", duration: 12},
      {name: "移动公司", duration: 15},
      {name: "政务中心", duration: 18},
      {name: "交警中队", duration: 21},
      {name: "十里市场", duration: 24},
      {name: "灵山职校", duration: 27},
      {name: "十里工业园", duration: 30},
      {name: "鹏大汽车城", duration: 33},
      {name: "见田村", duration: 36},
      {name: "天山电子厂", duration: 39},
      {name: "天山中学", duration: 42},
      {name: "檀圩镇政府", duration: 45},
      {name: "塘坡村", duration: 48},
      {name: "龙屈", duration: 51},
      {name: "县考试中心", duration: 54},
      {name: "那隆收费站", duration: 56},
      {name: "那隆派出所", duration: 58},
      {name: "塘表村", duration: 59},
      {name: "那隆中学", duration: 60}
    ]
  },
  {
    id: "802路",
    type: "城乡",
    start: "石塘",
    end: "灵山汽车总站",
    time: "07:30-18:30",
    interval: "30分钟",
    price: "0元",
    duration: "90分钟",
    stations: [
      {name: "石塘", duration: 0},
      {name: "化龙中学", duration: 5},
      {name: "六吉村", duration: 10},
      {name: "江儿口", duration: 15},
      {name: "大化", duration: 20},
      {name: "夏塘", duration: 25},
      {name: "平山林场", duration: 30},
      {name: "平山中学", duration: 35},
      {name: "平山", duration: 40},
      {name: "元眼坪", duration: 43},
      {name: "平坡村委", duration: 46},
      {name: "沙尤塘", duration: 49},
      {name: "大科塘", duration: 52},
      {name: "灵东水库", duration: 55},
      {name: "马肚塘", duration: 58},
      {name: "佛子中心学校", duration: 61},
      {name: "佛子卫生院", duration: 64},
      {name: "佛子中学", duration: 67},
      {name: "清湖村委", duration: 70},
      {name: "清湖", duration: 72},
      {name: "三岔塘加油站", duration: 74},
      {name: "马鞍山", duration: 76},
      {name: "园丰牧业", duration: 79},
      {name: "交通局", duration: 81},
      {name: "二医院", duration: 83},
      {name: "旧交通局", duration: 85},
      {name: "江南邮政", duration: 87},
      {name: "中医院", duration: 88},
      {name: "六峰万象城", duration: 89},
      {name: "步行街", duration: 90},
      {name: "红十字会医院", duration: 91},
      {name: "三海农行", duration: 92},
      {name: "国鹏宾馆", duration: 93},
      {name: "灵山汽车总站", duration: 90}
    ]
  },
  {
    id: "8028路",
    type: "城乡",
    start: "陆屋客运站",
    end: "聚龙湾",
    time: "07:00-18:00",
    interval: "30分钟",
    price: "15元",
    duration: "55分钟",
    stations: [
      {name: "陆屋客运站", duration: 0},
      {name: "三隆镇", duration: 18},
      {name: "交警大队", duration: 32},
      {name: "华源大厦", duration: 38},
      {name: "教育局", duration: 42},
      {name: "移动公司", duration: 46},
      {name: "汽车总站", duration: 49},
      {name: "国鹏宾馆", duration: 51},
      {name: "红十字", duration: 53},
      {name: "聚龙湾", duration: 55}
    ]
  },
  {
    id: "809路",
    type: "城乡",
    start: "伯劳",
    end: "二医院",
    time: "05:44-18:25",
    interval: "20分钟",
    price: "12元",
    duration: "110分钟",
    stations: [
      {name: "伯劳", duration: 0},
      {name: "邓阳村", duration: 6},
      {name: "六莲塘", duration: 12},
      {name: "檀宁街", duration: 18},
      {name: "天山中学", duration: 24},
      {name: "天山电子厂", duration: 30},
      {name: "见田村", duration: 36},
      {name: "鹏大汽车城", duration: 42},
      {name: "宇峰集团", duration: 48},
      {name: "十里工业园", duration: 54},
      {name: "职校", duration: 60},
      {name: "灵山五幼", duration: 65},
      {name: "交警大队", duration: 70},
      {name: "华源大厦", duration: 75},
      {name: "教育局", duration: 80},
      {name: "移动公司", duration: 84},
      {name: "汽车总站", duration: 88},
      {name: "国鹏宾馆", duration: 92},
      {name: "三海农行", duration: 95},
      {name: "红十字会医院", duration: 98},
      {name: "步行街", duration: 101},
      {name: "六峰万象城", duration: 104},
      {name: "中医院", duration: 106},
      {name: "江南邮政", duration: 108},
      {name: "旧交通局", duration: 109},
      {name: "二医院", duration: 110}
    ]
  }
];

module.exports = { lines: lines };